Don't quote queryCacheLimit (#31)
I believe this is an undocumented configuration, however when I tried to set it I kept getting the following errors on deploy

```
Error: MissingField("invalid type: string \"1000\", expected usize", 18)
```

which led me to find:
https://github.com/pgdogdev/pgdog/blob/9358fe3e859bd1abfb2e80f6c9cd44aaecf508f4/pgdog/src/config/general.rs#L135-L136
where the value is defined as a `usize`

Forking the repo, removing the `| quote` and using the forked version worker
correctly. I verified this by monitoring the `pgdog_query_cache_size` metric and
the value increased as I increased the value.